name: TestingReusable

on: 
  workflow_call: 

jobs:
  test:
    runs-on: 
      - self-hosted
      - linux
      - x64

    steps:
      - name: checking out
        uses: actions/checkout@v6

      - name: Listing files
        run: ls -ltrh
  

